spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:file:~/orders;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create-drop'
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: "0"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761//eureka
  instance:
    instance-id: "${spring.application.name}:${instanceId:${random.value}}"

axon:
  event-handling:
    processors:
      product-group:
        mode: subscribing
  serializer:
    events: JACKSON